export const ErrorCode = {
    passwordInUse: 'passwordInUse',
    badEmailFormat: 'badEmailFormat',
    emailInUse: 'emailInUse',
    phoneInUse: 'phoneInUse',
    usernameInUse: 'usernameInUse',
    invalidPassword: 'invalidPassword',
    noUser: 'noUser',
    rateLimited: 'rateLimited',
    serverError: 'serverError',
    photoUploadFailed: 'photoUploadFailed',
    fbAuthCancelled: 'fbAuthCancelled',
    fbAuthFailed: 'fbAuthFailed',
    appleAuthFailed: 'appleAuthFailed',
    smsNotSent: 'smsNotSent',
    invalidSMSCode: 'invalidSMSCode',
    googleSigninFailed: 'googleSigninFailed',
    requiresRecentLogin: 'requiresRecentLogin',
  }